/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.DbaMviewsJpaController;
import controllers.DbaTablesJpaController;
import controllers.DbaViewsJpaController;
import entities.DbaMviews;
import entities.DbaTables;
import entities.DbaViews;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class TablasFrame extends javax.swing.JFrame {

    private String usuario;
    
    private EntityManagerFactory emf;
    
    /**
     * Creates new form TablasFrame
     */
    public TablasFrame() {
        initComponents();
        init();
    }
    
    public TablasFrame(String usuario) {
        this.usuario = usuario;
        initComponents();
        init();
        System.out.println(usuario);
    }
    
    private void loadTables() {
        DbaTablesJpaController tablesController = new DbaTablesJpaController(emf);
        DbaViewsJpaController viewsController = new DbaViewsJpaController(emf);
        DbaMviewsJpaController mviewsController = new DbaMviewsJpaController(emf);
        
        List<DbaTables> tables = tablesController.getTablesByOwner(usuario);
        List<DbaViews> views = viewsController.getViewsByOwner(usuario);
        List<DbaMviews> mviews = mviewsController.getMviewsByOwner(usuario);
        
        DefaultListModel model = (DefaultListModel) leftList.getModel();
        
        System.out.println("tables: " + tables.size());
        System.out.println("views: " + views.size());
        System.out.println("mviews: " + mviews.size());
        
        for (DbaTables table : tables) {
            model.addElement(table.getTableName());
        }
        
        for (DbaViews view : views) {
            model.addElement(view.getViewName());
        }
        
        for (DbaMviews mview : mviews) {
            model.addElement(mview.getMviewName());
        }
    }
    
    private void init() {
        emf = Persistence.createEntityManagerFactory("ProyectoBasesPU");
        loadTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablasPanel = new javax.swing.JPanel();
        moverSeleccionButton = new javax.swing.JButton();
        moverTodosButton = new javax.swing.JButton();
        devolverSeleccionButton = new javax.swing.JButton();
        devolverTodosButton = new javax.swing.JButton();
        leftScrollPane = new javax.swing.JScrollPane();
        leftList = new javax.swing.JList<>();
        rightScrollPane = new javax.swing.JScrollPane();
        rightList = new javax.swing.JList<>();
        disponiblesLabel = new javax.swing.JLabel();
        seleccionadosLabel = new javax.swing.JLabel();
        verDetallesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(this.usuario);

        moverSeleccionButton.setText(">");
        moverSeleccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverSeleccionButtonActionPerformed(evt);
            }
        });

        moverTodosButton.setText(">>");
        moverTodosButton.setMaximumSize(new java.awt.Dimension(50, 23));
        moverTodosButton.setMinimumSize(new java.awt.Dimension(50, 23));
        moverTodosButton.setPreferredSize(new java.awt.Dimension(50, 23));
        moverTodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverTodosButtonActionPerformed(evt);
            }
        });

        devolverSeleccionButton.setText("<");
        devolverSeleccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverSeleccionButtonActionPerformed(evt);
            }
        });

        devolverTodosButton.setText("<<");
        devolverTodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverTodosButtonActionPerformed(evt);
            }
        });

        leftList.setModel(new DefaultListModel());
        leftScrollPane.setViewportView(leftList);

        rightList.setModel(new DefaultListModel());
        rightScrollPane.setViewportView(rightList);

        disponiblesLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        disponiblesLabel.setText("Disponibles");

        seleccionadosLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seleccionadosLabel.setText("Seleccionados");

        verDetallesButton.setText("Ver");
        verDetallesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetallesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablasPanelLayout = new javax.swing.GroupLayout(tablasPanel);
        tablasPanel.setLayout(tablasPanelLayout);
        tablasPanelLayout.setHorizontalGroup(
            tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablasPanelLayout.createSequentialGroup()
                        .addGroup(tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tablasPanelLayout.createSequentialGroup()
                                .addComponent(leftScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(devolverTodosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moverTodosButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moverSeleccionButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(devolverSeleccionButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(disponiblesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionadosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablasPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(verDetallesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tablasPanelLayout.setVerticalGroup(
            tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(disponiblesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tablasPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(seleccionadosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(leftScrollPane)
                        .addComponent(rightScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tablasPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(moverSeleccionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moverTodosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(devolverSeleccionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(devolverTodosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(verDetallesButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moverSeleccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverSeleccionButtonActionPerformed
        List<String> selectedValuesList = leftList.getSelectedValuesList();
        int[] selectedIndices = leftList.getSelectedIndices();
        
        if (selectedValuesList.size() > 0) {
            System.out.println("seleccionados: " + selectedValuesList.size());
            
            DefaultListModel leftListModel = (DefaultListModel) leftList.getModel();
            for (int i = selectedIndices.length - 1; i >= 0; --i) {    
                leftListModel.remove(selectedIndices[i]);
            }
            
            DefaultListModel rightListModel = (DefaultListModel) rightList.getModel();
            for (int i = 0; i < selectedIndices.length; ++i) {
                rightListModel.addElement(selectedValuesList.get(i));
            }
            
        }
        
    }//GEN-LAST:event_moverSeleccionButtonActionPerformed

    private void devolverSeleccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverSeleccionButtonActionPerformed
        List<String> selectedValuesList = rightList.getSelectedValuesList();
        int[] selectedIndices = rightList.getSelectedIndices();
        
        if (selectedValuesList.size() > 0) {
            System.out.println(selectedValuesList);
            
            DefaultListModel rightListModel = (DefaultListModel) rightList.getModel();
            for (int i = selectedIndices.length - 1; i >= 0; --i) {    
                rightListModel.remove(selectedIndices[i]);
            }
            
            DefaultListModel leftListModel = (DefaultListModel) leftList.getModel();
            for (int i = 0; i < selectedIndices.length; ++i) {
                leftListModel.addElement(selectedValuesList.get(i));
            }
            
        }
    }//GEN-LAST:event_devolverSeleccionButtonActionPerformed

    private void moverTodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverTodosButtonActionPerformed
        DefaultListModel leftListModel = (DefaultListModel) leftList.getModel();
        
        Object[] array = leftListModel.toArray();
        if (array.length > 0) {
            System.out.println("disponibles: " + array.length);
            for (int i = array.length - 1; i >= 0; --i) {    
                leftListModel.remove(i);
            }
            
            DefaultListModel rightListModel = (DefaultListModel) rightList.getModel();
            for (int i = 0; i < array.length; ++i) {
                rightListModel.addElement((String) array[i]);
            }
            
        }
    }//GEN-LAST:event_moverTodosButtonActionPerformed

    private void devolverTodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverTodosButtonActionPerformed
        DefaultListModel rightListModel = (DefaultListModel) rightList.getModel();
        
        Object[] array = rightListModel.toArray();
        if (array.length > 0) {
            
            for (int i = array.length - 1; i >= 0; --i) {    
                rightListModel.remove(i);
            }
            
            DefaultListModel leftListModel = (DefaultListModel) leftList.getModel();
            for (int i = 0; i < array.length; ++i) {
                leftListModel.addElement((String) array[i]);
            }
            
        }
    }//GEN-LAST:event_devolverTodosButtonActionPerformed

    private void verDetallesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetallesButtonActionPerformed
        DefaultListModel rightListModel = (DefaultListModel) rightList.getModel();
        
        Object[] array = rightListModel.toArray();
        if (array.length > 0) {
            // TODO: buscar datos de las tablas/vistas seleccionadas en la base de datos
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona al menos una tabla/vista.");
        }
    }//GEN-LAST:event_verDetallesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devolverSeleccionButton;
    private javax.swing.JButton devolverTodosButton;
    private javax.swing.JLabel disponiblesLabel;
    private javax.swing.JList<String> leftList;
    private javax.swing.JScrollPane leftScrollPane;
    private javax.swing.JButton moverSeleccionButton;
    private javax.swing.JButton moverTodosButton;
    private javax.swing.JList<String> rightList;
    private javax.swing.JScrollPane rightScrollPane;
    private javax.swing.JLabel seleccionadosLabel;
    private javax.swing.JPanel tablasPanel;
    private javax.swing.JButton verDetallesButton;
    // End of variables declaration//GEN-END:variables
}
